yarnPath: ".yarn/releases/yarn-berry.cjs"
packageExtensions:
  "@aws-amplify/storage@*":
    dependencies:
      "@aws-amplify/auth": "*"
      "aws-sdk": "*"
  "@aws-amplify/datastore@*":
    dependencies:
      "crypto-js/core": "*"
      "crypto-js": "*"
      "@aws-amplify/auth": "*"
      "@aws-amplify/cache": "*"

  "@aws-amplify/ui-react@*":
    dependencies:
      "@aws-amplify/auth": "*"
  grommet-controls@*:
    dependencies:
      "tslib": "*"

  styled-components@*:
    dependencies:
      react-is: "*"

  "@aws-amplify/api@*":
    dependencies:
      "@aws-amplify/cache": "*"
      "@aws-amplify/auth": "*"
