packageExtensions:
  "@aws-amplify/api@*":
    dependencies:
      "@aws-amplify/auth": "*"
      "@aws-amplify/cache": "*"
  "@aws-amplify/datastore@*":
    dependencies:
      "@aws-amplify/auth": "*"
      "@aws-amplify/cache": "*"
      crypto-js: "*"
      crypto-js/core: "*"
  "@aws-amplify/storage@*":
    dependencies:
      "@aws-amplify/auth": "*"
      aws-sdk: "*"
  "@aws-amplify/ui-react@*":
    dependencies:
      "@aws-amplify/auth": "*"
  grommet-controls@*:
    dependencies:
      tslib: "*"
  styled-components@*:
    dependencies:
      react-is: "*"

yarnPath: .yarn/releases/yarn-3.0.0.cjs
nodeLinker: node-modules
