version: "2.1"

services:
  localstack:
    container_name: tnm-admin-localstack
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=appsync,route53,cloudformation,cloudfront,s3,dynamodb,lambda,iam
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=us-east-1

    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
