name: Build test and deploy
on:
  push:
    branches:
      - main
      - test
      - develop

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Configure node 14
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Yarn install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

  unit-test:
    name: Run eslint and unit tests
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Configure node 14
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Lint
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: lint
      - name: Test
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test:ci

  deploy:
    name: Deploy application
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Configure node 14
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Configure amplify (Prod)
        uses: ambientlight/amplify-cli-action@0.2.1
        if: ${{ endsWith(github.ref, 'main') }}
        with:
          amplify_command: configure
          amplify_env: prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Configure amplify (Test)
        uses: ambientlight/amplify-cli-action@0.2.1
        if: ${{ endsWith(github.ref, 'test') }}
        with:
          amplify_command: configure
          amplify_env: test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Configure amplify (Dev)
        uses: ambientlight/amplify-cli-action@0.2.1
        if: ${{ endsWith(github.ref, 'develop') }}
        with:
          amplify_command: configure
          amplify_env: dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Yarn install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: deploy
        uses: ambientlight/amplify-cli-action@0.2.1
        with:
          amplify_command: publish
          amplify_env: prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
