name: Deploy Application to Prod
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Application version'
        required: true
        default: 'latest'
  registry_package:
    types: [published, updated]

jobs:
  deploy-to-prod:
    name: Deploy To Prod
    runs-on: ubuntu-latest
    steps:
      - name: Configure node 12
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Configure Package Registry Auth
        run: |
          echo "//npm.pkg.github.com/:_authToken=$GH_TOKEN" > ~/.npmrc
          echo "@benwainwright:registry=https://npm.pkg.github.com" >> ~/.npmrc

        env: 
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Install Package
        run: npm install -g @benwainwright/tnm

      - name: Get package directory
        run: echo "PACKAGE_DIR=$(npm list -g | head -1)/node_modules/@benwainwright/tnm" >> $GITHUB_ENV

      - name: Turnstyle
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 30
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Backend
        run: |
          cd $PACKAGE_DIR
          npm run deploy:backend:prod
        env:
          DEPLOYMENT_ENVIRONMENT: prod
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID_BACKEND }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY_BACKEND }}
          AWS_REGION: us-east-1

      - name: Deploy Frontend
        run: |
          cd $PACKAGE_DIR
          cp backend-outputs.json build
          cp CHANGELOG.md build
          npm run deploy:frontend:prod
        env:
          DEPLOYMENT_ENVIRONMENT: prod
          AWS_ACCESS_KEY_ID: ${{ secrets.FRONTEND_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.FRONTEND_KEY }}
          AWS_REGION: us-east-1
