name: Deploy
on:
  registry_package:
    types: [published, updated]

jobs:
  deploy-to-test:
    name: Deploy To Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure node 12
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Write .npmrc
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" >> ~/.npmrc

      - name: Install Package
        run: yarn global add @benwainwright/tnm

      - name: Change to package directory
        run: cd $(yarn global dir)/node_modules/@benwainwright/tnm

      - name: Turnstyle
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 30
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Backend
        run: yarn deploy:backend
        env:
          DEPLOYMENT_ENVIRONMENT: test
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Deploy Frontend
        run: yarn deploy:frontend
        env:
          DEPLOYMENT_ENVIRONMENT: test
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Get Cloudfront distribution ID
        run: echo "CLOUDFRONT_ID=$(cat src/frontend-outputs.json | jq --raw-output '.[].CloudFrontDistributionId')" > $GITHUB_ENV
      - name: Install AWS CLI
        uses: chrislennon/action-aws-cli@v1.1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Invalidate Cloudfront cache
        run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/index.html"
        env:
          DEPLOYMENT_ENVIRONMENT: test
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

  deploy-to-prod:
    name: Deploy To Prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure node 12
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Write .npmrc
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" >> ~/.npmrc

      - name: Install Package
        run: yarn global add @benwainwright/tnm

      - name: Change to package directory
        run: cd $(yarn global dir)/node_modules/@benwainwright/tnm

      - name: Turnstyle
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 30
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Backend
        run: yarn deploy:backend
        env:
          DEPLOYMENT_ENVIRONMENT: prod
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Deploy Frontend
        run: yarn deploy:frontend
        env:
          DEPLOYMENT_ENVIRONMENT: prod
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Get Cloudfront distribution ID
        run: echo "CLOUDFRONT_ID=$(cat src/frontend-outputs.json | jq --raw-output '.[].CloudFrontDistributionId')" > $GITHUB_ENV
      - name: Install AWS CLI
        uses: chrislennon/action-aws-cli@v1.1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Invalidate Cloudfront cache
        run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/index.html"
        env:
          DEPLOYMENT_ENVIRONMENT: prod
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
